In [2]:
import joblib
from lightfm import LightFM
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors

In [3]:
model  : LightFM = joblib.load('models/amazon-book-reviews-no-item-features-model.pkl')

In [4]:
bias, components = model.get_item_representations() 
item_representations = np.concatenate([bias.reshape(-1,1), components], axis=1)

In [7]:
neighbors = NearestNeighbors(n_neighbors=10).fit(item_representations)

In [13]:
distances, indices = neighbors.kneighbors(item_representations[5:6])
indices

array([[     5,      6, 137985, 200474, 106778,  35049,  42526,  86943,
        204820,  17609]])

In [14]:
id = 5
target_item = item_representations[id]

dist = np.array([np.linalg.norm(x - target_item) for x in item_representations])
dist_indices_sorted = dist.argsort()
dist_indices_sorted[:10]
#dist_indices_sorted = dist_indices_sorted[dist_indices_sorted != id]

array([     5,      6, 137985, 200474, 106778,  35049,  42526,  86943,
       204820,  17609])

In [32]:
dist_indices_sorted[:5]

array([     6, 137985, 200474, 106778,  35049])